<?php

defined('AIW_CMS') or die;

return [
    'Blog'           => 'BLOG_BLOG',
    'ConfigControl'  => 'CONFIG_CONTROL',
    'Contacts'       => 'CONTACTS_TITLE',
    'Doc'            => 'DOC_DOC',
    'ItemController' => 'BRC_ITEM_CONTROLLER',
    'Main'           => 'OV_HOME',
    'Review'         => 'REVIEW_REVIEWS',
    'Test'           => 'BRC_TEST',
    'Ticket'         => 'TICKET_TICKETS',
    'TicketAnswer'   => 'BRC_TICKET_ANSWER',
    'User'           => 'USER_USERS',
    'ViewLog'        => 'OV_ATTENDANCE',
    'Add'                => 'OV_CREATE',
    'Advertising'        => 'USER_ADVERTISING',
    'Balance'            => 'USER_BALANCE',
    'BalanceClear'       => 'INFO_CLEAR_FILTERS',
    'ChangePass'         => 'USER_CHANGE_PASSWORD',
    'Control'            => 'OV_CONTROL',
    'ControlClear'       => 'INFO_CLEAR_FILTERS',
    'Edit'               => 'OV_EDITING',
    'EditHistory'        => 'OV_EDIT_HISTORY',
    'EditHistoryClear'   => 'INFO_CLEAR_FILTERS',
    'Index'              => '',
    'Login'              => 'USER_LOGIN',
    'Logout'             => 'USER_LOGOUT',
    'MyBalance'          => 'USER_BALANCE',
    'MyBalanceClear'     => 'INFO_CLEAR_FILTERS',
    'MyEditHistory'      => 'OV_EDIT_HISTORY',
    'MyEditHistoryClear' => 'INFO_CLEAR_FILTERS',
    'NetClear'           => 'INFO_CLEAR_FILTERS',
    'PassReset'          => 'USER_RESET_PASSWORD',
    'RefCode'            => 'USER_REFERRAL_LINK',
    'View'               => '',
    'ChangeStatus'       => 'TICKET_STATUS_CHANGE',
    'My'                 => 'OV_CONTROL',
    'MyClear'            => 'INFO_CLEAR_FILTERS',
    'NewTicket'          => 'TICKET_ADD',
    'Competition'        => 'COMAIN_COMPETITIONS',
    'Admin'              => 'ADMIN_ADMIN',
];
